version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Group all updates into a single PR
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 01:00
      timezone: Canada/Pacific
    groups:
      all-actions:
        patterns: [ "*" ]

  # Maintain dependencies for Python packages
  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: daily